### ISSUE TITLE
EasyDialog in fragment

### ISSUE THREAD

**Issue by iffanmajid** [michaelye/EasyDialog#12]
I cannot target EasyDialog when it called in onCreate or onViewCreated. How to use it?

**Comment by michaelye** [comment]
Hi,I think maybe in onCreate or onViewCreated method,the views not been inflated,so EasyDialog can NOT get the location,so,just try

view.postDelayed(new Runnable()
        {
            @Override
            public void run()
            {
                  //show EasyDialog after 200ms
            }
        }, 200);

//or

final Handler handler = new Handler();
handler.postDelayed(new Runnable() 
{
        @Override
        public void run()
       {
                //show EasyDialog after 200ms
       }
}, 200);
