### ISSUE TITLE
Listener for close tool tip or make public onDialogDismiss

### ISSUE THREAD

**Issue by pablocarballo** [michaelye/EasyDialog#15]
Hi,
I need know when the tooltip is gone. with listener or override method onDialogDismiss can resolve this. Thanks!.

**Comment by michaelye** [comment]
@pablocarballo Hi,I am not very clear what you mean,do you mean you want to get a callback listener when the dialog is dismissed?

**Comment by michaelye** [comment]
@pablocarballo I add a dialog dismiss listener callback, so you can use EasyDialog like this:

> easyDialog.setOnEasyDialogDismissed(new EasyDialog.OnEasyDialogDismissed()
>                         {
>                             @Override
>                             public void onDismissed()
>                             {
>                                 Toast.makeText(MainActivity.this, "dismiss", Toast.LENGTH_SHORT).show();
>                             }
>                         })

dependencies {
    compile 'com.github.michaelye.easydialog:easydialog:1.4'
}

if you still have any questions,let me know,thanks : )

**Comment by pablocarballo** [comment]
Exactly! Nice solution. Many thanks.
