### ISSUE TITLE
Ability to set text dynamically and set view

### ISSUE THREAD

**Issue by danvinokour** [michaelye/EasyDialog#19]
Hi,

I have many tooltips and it seems that i have to create different layout file for each tooltip which would be a lot.

I think it would be really good if we could set layout but each time we create EasyDialog we would be able to set different text or just to set custom view which we will inflate with the custom layout and text.

**Comment by michaelye** [comment]
@danvinokour Sorry,My first language is not English,So I am not very clear about what you mean.Could you please explain it in more detail.maybe you could show me some usage or something whatever to make me more easier to understand.Thanks.

**Comment by danvinokour** [comment]
Hi, my bad...didnt see the setLayout function :)

**Comment by michaelye** [comment]
@danvinokour It's Ok :D
