### ISSUE TITLE
Dialog is not attached on action bar

### ISSUE THREAD

**Issue by Mohsin92** [michaelye/EasyDialog#27]
Hi Michaelye,

I am trying to attached dialog on action bar menu item,

But here in .setLocation(view) need view I am not able to set here menu item.

Please check this from your end.

Thank you.

**Comment by michaelye** [comment]
@Mohsin92 
Hi,is this issue can fix your problem? 
[ISSUE](https://github.com/michaelye/EasyDialog/issues/1)

**Comment by Mohsin92** [comment]
Thank you so much michaelye issue got solve.

One more thing can we change color of dialog border ?

By default its coming grey color on border I need white color Is it possible 

Your help will be highly appreciated.

Thank you.

**Comment by michaelye** [comment]
It's Ok.Setting border color is a good feature,I've considered about it, but I have no extra time to finish this feature, maybe it would be added in future time.Sorry about that.

**Comment by Mohsin92** [comment]
@michaelye : its ok , well you can close this issue now.

Thank you :+1:
