### ISSUE TITLE
Screen rotation

### ISSUE THREAD

**Issue by Anth06ny** [michaelye/EasyDialog#3]
Hi, 

thank you for your library.
I have a problem with your dialog when activity recreated (for exemple during screen rotation).
I have IllegalArgumentException.

I call "EasyDialog.dismiss()" method on "Activity.onStop()" and if I remove this instruction it's works.
How can I close dialog when I left the screen ?

I hope you have understand my problem.

thank you

Anthony

Stacktrace

 java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{3127ddcb V.E..... R......D 0,0-1280,736} not attached to window manager
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.app.Dialog.dismissDialog(Dialog.java:341)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.app.Dialog.dismiss(Dialog.java:324)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at com.michael.easydialog.EasyDialog$3.onAnimationEnd(EasyDialog.java:457)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:854)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1171)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:722)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:738)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:549)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
10-15 17:42:25.690 32490-32490/temp.com.payzenmpos.dev E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by michaelye** [comment]
Hi，Anthony

Thank you for using EasyDialog.According to your description,I test it in
my cellphone,when I rotate the screen,the dialog would be close
automatic.So I am not very clear with why you get the ERROR.

Then,looking into the log   _E/AndroidRuntime: at com.michael.easydialog._
_EasyDialog$3.onAnimationEnd(EasyDialog.java:457)_

I guess it's because that, your activity has finished,but the dialog still
alive(because the animation in dialog take some times),so when the
animation ended,  then running _dialog.dismiss();_
would get the ERROR.

It's a BUG of EasyDialog, I would fix it late,Thanks very much!

2015-10-15 23:54 GMT+08:00 Anth06ny notifications@github.com:

**Comment by Anth06ny** [comment]
Yes it's the problem.
I'm wainting for your fix.

Thanks

**Comment by michaelye** [comment]
Hi, Anthony

I fixed the bug,and update the code and repository.

You could use the new repository by

_compile 'com.github.michaelye.easydialog:easydialog:1.1'_

Whether it works for you,please let me know : )

2015-10-16 15:06 GMT+08:00 Anth06ny notifications@github.com:

**Comment by Anth06ny** [comment]
Perfect :)

**Comment by michaelye** [comment]
@Anth06ny :)
