### ISSUE TITLE
auto close the tool tip after some time

### ISSUE THREAD

**Issue by kumarbanty** [michaelye/EasyDialog#30]
How to automatically make the tool tip disappear after some time?

**Comment by michaelye** [comment]
This feature had been issued before.I've consider about it,but I have no extra time to finish it.For now, you may handle it by yourself,for example:

```
Timer timer = new Timer();  
timer.schedule(new TimerTask()
{ 
    @Override
    public void run()   
    {  
            //TODO dismiss the Dialog 
    }  
}, 3000);//after 3seconds
```

**Comment by kumarbanty** [comment]
Thank you
