### ISSUE TITLE
remove views before attaching

### ISSUE THREAD

**Issue by mp3por** [michaelye/EasyDialog#8]
Please refactor the .show() method to remove the current views in the llContent before adding the new one. " llcontent.removeAllViews() "

This will greatly increase reusability of the dialog and it is very troublesome to do it manually every time.

Thank you

**Comment by michaelye** [comment]
@mp3por ok, it will be fixed soon.Thanks for the issue.

**Comment by michaelye** [comment]
@mp3por fixed this issue

see:

compile 'com.github.michaelye.easydialog:easydialog:1.2'
